source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GMEllipticCurveCrypto_Example' do
  pod 'GMEllipticCurveCrypto', :path => '../'
end

target 'GMEllipticCurveCrypto_Tests' do
  pod 'GMEllipticCurveCrypto', :path => '../'

  
end
